baseURL = 'https://www.victhor.net.br/'
locale = 'en-us'
title = 'Victhor Foster'
theme = 'hugo-flex'

[params]
    color = 'teal'
    width = '42rem'
    divider = '\2500\2500'
    footer = '(c) 2025 Victhor Foster. All rights reserved.'
    # rss = 'To subscribe to this RSS feed, copy its address and paste it into your    favorite feed reader.'
    favicon = 'false'
    noclasses = '&nc false'
    katex = '0.16.22'
    linkicons = 'false'
    summaries = 'false'
    schema = 'false'
    opengraph = 'false'
    twittercards = 'false'

    [params.utterances]
         repo = ''
         issueterm = ''
         theme = ''
   
    [params.netlify]
         honeypot = 'false'
         recaptcha = 'false'

[markup]
    [markup.highlight]
         noClasses = 'false'
    [markup.goldmark]
         [markup.goldmark.extensions]
              [markup.goldmark.extensions.passthrough]
                  enable = 'false'
                  [markup.goldmark.extensions.passthrough.delimiters]
                      block = [ '\[', '\]', '$$', '$$' ]
                      inline = [ '\(', '\)' ]

[menu]
    main = [#{ name = 'About', pageRef = '/about', weight = '1' }, 
            { name = 'Posts', pageRef = '/post', weight = '2' } ]

                        
